
services:
  ruuvi-gateway:
    image: ghcr.io/scrin/ruuvi-go-gateway
    container_name: ruuvi-go-gateway
    restart: unless-stopped
    depends_on:
      mosquitto:
        condition: service_healthy
        restart: true
    cap_add:
      - NET_ADMIN
    network_mode: host
    privileged: true              
    volumes:
      - ./ruuvi-gateway-config.yml:/config.yml:ro

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"  # WebSocket (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: always
    network_mode: host  # recommended for full discovery support
    volumes:
      - ./homeassistant:/config
    environment:
      - TZ=Europe/Helsinki
