scan_duration: 5s  # Scan every 5 seconds (default)
use_decoded_data: true  # Enables automatic decoding of sensor packets

mqtt:
  host: "localhost"
  port: 1883
  topic_prefix: "ruuvi"
  client_id: "ruuvi-gateway"
  qos: 0